# Generated by Django 3.2.1 on 2021-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_regis',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
