# Generated by Django 3.2.1 on 2021-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0002_hr_regis_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('phonenumber', models.IntegerField(max_length=12)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
