# Generated by Django 3.2.1 on 2021-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_app', '0003_hr_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='hr_regis',
        ),
    ]
